# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
pygments: true

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : John Crowe
tagline : Will Program For Coffee
author :
  email : thecrow1213@gmail.com
  github : TheCrow1213
  twitter : TheCrow1213
  coderwall : TheCrow1213
  linkedin : johnbcrowe
  googleplus : 107133389378228106210
  feedbaname : thecrow1213

# The production_url is only used when full-domain names are needed
# such as sitemap.txt 
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.com, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://thecrow1213.github.io
rss_path: http://thecrow1213.github.io/rss.xml